
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool, T4ConfigDnx.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace T4ConfigDnx
{
	using System;

	public class AppSettings 
	{
		public string SiteTitle { get; set; }
		public string SecondProperty { get; set; }
		public int PullInterval { get; set; }
		public decimal FactorValue { get; set; }
		public Guid ApiAccessId { get; set; }
	}
	
}
